name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.4.0-alpine3.17

    - name: Build the application
      run: |
        echo "Building the application"
        npm install
        npm run build
        cp dist /mnt/production

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19.4.0-alpine3.17

    - name: Test the application
      run: |
        echo "Testing the application"
        npm run test
